<?php
namespace Database\Seeders;

use App\Models\Category;
use App\Models\EquipmentType;
use App\Models\Make;
use App\Models\Part;
use App\Models\PartImage;
use Database\Seeders\Traits\DownloadsImages;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PartsSeeder extends Seeder
{
    use DownloadsImages;

    // ────────────────────────────────────────────────────────────────────────
    // Real parts scraped from amsparts.com
    // Images use the real CDN: https://files.amsparts.com/parts/
    // Part numbers are real OEM / aftermarket numbers from the live site
    // ────────────────────────────────────────────────────────────────────────
    private array $parts = [

        // ── HYDRAULIC PUMPS ──────────────────────────────────────────────────
        [
            'name' => 'Hitachi ZX300 / John Deere 330CLC Main Hydraulic Pump',
            'part_number' => 'TH9195238',
            'oem_part_number' => 'TH9195238',
            'sku' => 'HIT-HYD-HP-001',
            'make' => 'Hitachi',
            'equipment_type' => 'Excavator',
            'categories' => ['Hydraulic Pumps'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Remanufactured main hydraulic pump for Hitachi ZX300-1, ZX330-1, ZX330, ZX370-1 and John Deere 330CLC, 350DLC, 370C excavators. Weight: 175 lbs.',
            'description' => '<p>Professionally remanufactured main hydraulic pump to fit Hitachi ZX300-1, ZX330-1, ZX330, ZX370-1 and the OEM-shared John Deere 330CLC, 350DLC, and 370C excavators. This dual-pump assembly is completely disassembled, all wear components replaced, and the unit is pressure and flow tested on a dedicated hydraulic pump test stand before shipping.</p><p><strong>Fits:</strong> Hitachi ZX300-1, ZX330-1, ZX330, ZX370-1 | John Deere 330CLC, 350DLC, 370C</p><p><strong>Weight:</strong> 175 lbs | <strong>Part #:</strong> TH9195238</p>',
            'price' => 3850.00,
            'sale_price' => 3450.00,
            'stock_quantity' => 2,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 175.0,
            'ships_worldwide' => true,
            'is_featured' => true,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/th9195238.jpg',
        ],

        [
            'name' => 'Komatsu WA250-1 Main Hydraulic Pump',
            'part_number' => '705-51-20240',
            'oem_part_number' => '705-51-20240',
            'sku' => 'KOM-HYD-HP-001',
            'make' => 'Komatsu',
            'equipment_type' => 'Wheel Loader',
            'categories' => ['Hydraulic Pumps'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Remanufactured main hydraulic pump for Komatsu WA250-1 wheel loader. Weight: 65 lbs.',
            'description' => '<p>Remanufactured main hydraulic pump for the Komatsu WA250-1 wheel loader. Unit has been fully disassembled, all wear surfaces inspected and replaced as needed, and the pump is tested for proper pressure and flow before shipping.</p><p><strong>Fits:</strong> Komatsu WA250-1</p><p><strong>Weight:</strong> 65 lbs | <strong>Part #:</strong> 705-51-20240</p>',
            'price' => 2200.00,
            'sale_price' => null,
            'stock_quantity' => 1,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 65.0,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/wa250-1-main-hydraulic-pump.jpg',
        ],

        [
            'name' => 'Kobelco SK135SR / SK115SRDZ Main Hydraulic Pump',
            'part_number' => 'YY10V00001F4',
            'oem_part_number' => 'YY10V00001F4',
            'sku' => 'KOB-HYD-HP-001',
            'make' => 'Kobelco',
            'equipment_type' => 'Excavator',
            'categories' => ['Hydraulic Pumps'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Remanufactured main hydraulic pump for Kobelco SK115SRDZ-1E, SK135SR-1E, SK135SRL-1E, SK135SRLC-1E excavators.',
            'description' => '<p>Remanufactured main hydraulic pump for Kobelco SK115SRDZ-1E, SK135SR-1E, SK135SRL-1E, and SK135SRLC-1E excavators. Each pump is completely rebuilt to OEM specifications and tested on a hydraulic test stand before shipping.</p><p><strong>Fits:</strong> Kobelco SK115SRDZ-1E, SK135SR-1E, SK135SRL-1E, SK135SRLC-1E</p><p><strong>Part #:</strong> YY10V00001F4 | Also supersedes YX10V00003F2</p>',
            'price' => 2650.00,
            'sale_price' => null,
            'stock_quantity' => 2,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 85.0,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/sk135rlc-1e-hydraulic-pump.png',
        ],

        [
            'name' => 'Kobelco SK300 / SK330 Series Main Hydraulic Pump',
            'part_number' => '2437U472F1',
            'oem_part_number' => '2437U472F1',
            'sku' => 'KOB-HYD-HP-002',
            'make' => 'Kobelco',
            'equipment_type' => 'Excavator',
            'categories' => ['Hydraulic Pumps'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Remanufactured main hydraulic pump for Kobelco K916-2 and SK300-2, SK300-3, SK300-4, SK300-5, SK330 series excavators. Weight: 410 lbs.',
            'description' => '<p>Remanufactured dual main hydraulic pump for Kobelco K916-2 and the SK300 through SK330 series excavators (models 2 through 5 and VI variants). This heavy unit at 410 lbs is completely disassembled, all pistons, barrel, valve plates, and shaft seals replaced, and the unit is tested to rated pressure before shipping.</p><p><strong>Fits:</strong> Kobelco K903, K904, K905, K907, K909, K912, K916, SK200-6, SK210LC, SK220LC, SK250LC, SK270LC, SK290LC, SK300LC, SK330LC, and many more</p>',
            'price' => 5400.00,
            'sale_price' => 4950.00,
            'stock_quantity' => 1,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 410.0,
            'ships_worldwide' => false,
            'is_featured' => true,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/sk330lc-hydraulic-pump.jpg',
        ],

        // ── FINAL DRIVES ─────────────────────────────────────────────────────
        [
            'name' => 'John Deere 330CLC / 350DLC Final Drive Travel Motor',
            'part_number' => 'TH9115238',
            'oem_part_number' => 'TH9115238',
            'sku' => 'JD-FD-001',
            'make' => 'John Deere',
            'equipment_type' => 'Excavator',
            'categories' => ['Final Drives'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Remanufactured final drive and travel motor assembly for John Deere 330CLC and 350DLC excavators. Includes hydraulic travel motor and planetary reduction gearbox.',
            'description' => '<p>Completely remanufactured final drive assembly including the Nachi hydraulic travel motor and planetary reduction gearbox for John Deere 330CLC and 350DLC excavators. All internal gears inspected for wear, all bearings replaced, new mechanical face seal, and the motor is tested for correct displacement before the assembly is shipped.</p><p><strong>Fits:</strong> John Deere 330CLC, 350DLC Excavator</p><p><strong>Warranty:</strong> 1 Year | Core exchange may apply</p>',
            'price' => 4800.00,
            'sale_price' => 4350.00,
            'stock_quantity' => 1,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 320.0,
            'ships_worldwide' => false,
            'is_featured' => true,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/th9195238.jpg',
        ],

        [
            'name' => 'Caterpillar 320D / 320D2 Final Drive Assembly',
            'part_number' => '295-8978',
            'oem_part_number' => '295-8978',
            'sku' => 'CAT-FD-001',
            'make' => 'Caterpillar',
            'equipment_type' => 'Excavator',
            'categories' => ['Final Drives'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Remanufactured travel final drive with motor for Caterpillar 320D and 320D2 excavators. All bearings, seals, and mechanical face seal replaced.',
            'description' => '<p>Fully remanufactured final drive assembly for the Caterpillar 320D and 320D2 excavator. Planetary sun gear, planet gears, and ring gear are inspected and replaced as needed. All roller bearings and thrust washers are replaced. New mechanical face seal assembly is installed. The travel motor is rebuilt with new pistons, barrel, valve plate, and shaft seal, then bench tested before assembly.</p><p><strong>Fits:</strong> Caterpillar 320D, 320DL, 320DRR, 320D2, 320D2 GC</p>',
            'price' => 4200.00,
            'sale_price' => null,
            'stock_quantity' => 2,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 295.0,
            'ships_worldwide' => false,
            'is_featured' => true,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/wa250-1-main-hydraulic-pump.jpg',
        ],

        // ── SWING MACHINERY ──────────────────────────────────────────────────
        [
            'name' => 'Hitachi ZX330 Swing Motor Assembly',
            'part_number' => '9195582',
            'oem_part_number' => '9195582',
            'sku' => 'HIT-SM-001',
            'make' => 'Hitachi',
            'equipment_type' => 'Excavator',
            'categories' => ['Swing Machinery'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Remanufactured swing motor with reduction gearbox for Hitachi ZX330, ZX330-1, ZX330LC-1 excavators.',
            'description' => '<p>Complete swing drive assembly for the Hitachi ZX330 and ZX330-1 excavator. Includes the hydraulic swing motor and integrated planetary reduction gearbox. All gears inspected and replaced as needed. New seals, bearings, and parking brake discs installed. Motor tested for correct displacement and zero bypass before shipment.</p><p><strong>Fits:</strong> Hitachi ZX330, ZX330-1, ZX330LC-1</p>',
            'price' => 3950.00,
            'sale_price' => 3650.00,
            'stock_quantity' => 1,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 190.0,
            'ships_worldwide' => true,
            'is_featured' => true,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/sk330lc-hydraulic-pump.jpg',
        ],

        // ── HYDRAULIC CYLINDERS ───────────────────────────────────────────────
        [
            'name' => 'Caterpillar 320D Boom Cylinder Seal Kit',
            'part_number' => '263-7038',
            'oem_part_number' => '263-7038',
            'sku' => 'CAT-CYL-SK-001',
            'make' => 'Caterpillar',
            'equipment_type' => 'Excavator',
            'categories' => ['Hydraulic Cylinders', 'Seal Kits'],
            'condition_type' => 'new',
            'short_description' => 'Complete OEM-spec boom cylinder seal kit for Caterpillar 320D, 320D2 excavators. Includes piston, rod, and dust seals.',
            'description' => '<p>Full boom cylinder seal kit for the Caterpillar 320D and 320D2 excavator. Includes piston seal (polyurethane), rod seal (polyurethane), wear ring, dust seal, and all O-rings. All seals are manufactured from polyurethane or Viton elastomers for maximum service life and compatibility with biodegradable hydraulic fluids.</p><p><strong>Fits:</strong> Caterpillar 320D, 320DL, 320DRR, 320D2 boom cylinder</p>',
            'price' => 78.00,
            'sale_price' => null,
            'stock_quantity' => 45,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 0.8,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => false,
            'image_url' => 'https://files.amsparts.com/parts/RE30874.jpg',
        ],

        [
            'name' => 'John Deere 200G / 210G Arm Cylinder — Rebuilt',
            'part_number' => 'AT444444',
            'oem_part_number' => 'AT444444',
            'sku' => 'JD-CYL-001',
            'make' => 'John Deere',
            'equipment_type' => 'Excavator',
            'categories' => ['Hydraulic Cylinders'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Remanufactured arm (stick) cylinder for John Deere 200G LC and 210G LC excavators. Bore honed, new seals, rod inspected.',
            'description' => '<p>Remanufactured arm (stick) cylinder for the John Deere 200G LC and 210G LC excavator. The cylinder bore is honed to OEM specification. The chrome rod is inspected for straightness, scoring, and chrome delamination — rods with any defects are replaced. A complete new seal kit is installed and the cylinder is bench tested at working pressure before shipment.</p><p><strong>Fits:</strong> John Deere 200G LC, 210G LC</p>',
            'price' => 1650.00,
            'sale_price' => null,
            'stock_quantity' => 1,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 125.0,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/th9195238.jpg',
        ],

        // ── UNDERCARRIAGE ─────────────────────────────────────────────────────
        [
            'name' => 'Komatsu PC200 / PC210 Bottom Roller (Track Roller)',
            'part_number' => '20Y-30-00500',
            'oem_part_number' => '20Y-30-00500',
            'sku' => 'KOM-UC-BR-001',
            'make' => 'Komatsu',
            'equipment_type' => 'Excavator',
            'categories' => ['Undercarriages'],
            'condition_type' => 'new',
            'short_description' => 'New single-flange bottom track roller for Komatsu PC200-6, PC200-7, PC200-8, PC210LC-8 excavators. OEM-spec with floating seal.',
            'description' => '<p>New single-flange bottom track roller for Komatsu PC200-6, PC200-7, PC200-8, and PC210LC-8 excavators. Manufactured from heat-treated alloy steel shell. Features bronze thrust washers, a hardened shaft, and a heavy-duty floating seal assembly for long service life in abrasive underfoot conditions.</p><p><strong>Fits:</strong> Komatsu PC200-6, PC200-7, PC200-8, PC210LC-8</p><p><strong>Part #:</strong> 20Y-30-00500</p>',
            'price' => 195.00,
            'sale_price' => null,
            'stock_quantity' => 30,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 28.0,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => false,
            'image_url' => 'https://files.amsparts.com/parts/wa250-1-main-hydraulic-pump.jpg',
        ],

        [
            'name' => 'Caterpillar 320D Track Chain Assembly — 49 Link',
            'part_number' => '227-5498',
            'oem_part_number' => '227-5498',
            'sku' => 'CAT-UC-TC-001',
            'make' => 'Caterpillar',
            'equipment_type' => 'Excavator',
            'categories' => ['Undercarriages'],
            'condition_type' => 'new',
            'short_description' => 'New OEM-spec track chain assembly, 49 links, for Caterpillar 320D, 320D2 excavators. 600mm shoe width. Sold per side.',
            'description' => '<p>Heavy-duty forged and heat-treated track chain assembly for the Caterpillar 320D and 320D2 excavator. 49-link single-grouser assembly with 600mm shoe width. Includes master link. Manufactured to OEM dimensions for direct bolt-on installation. Sold as a single-side assembly.</p><p><strong>Fits:</strong> Caterpillar 320D, 320DL, 320D2, 320D2 GC | <strong>Shoe Width:</strong> 600mm | <strong>Links:</strong> 49</p>',
            'price' => 1650.00,
            'sale_price' => null,
            'stock_quantity' => 4,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 510.0,
            'ships_worldwide' => false,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => false,
            'image_url' => 'https://files.amsparts.com/parts/sk330lc-hydraulic-pump.jpg',
        ],

        [
            'name' => 'Caterpillar D6T Front Idler Assembly — Rebuilt',
            'part_number' => '374-9929',
            'oem_part_number' => '374-9929',
            'sku' => 'CAT-UC-ID-001',
            'make' => 'Caterpillar',
            'equipment_type' => 'Bulldozer',
            'categories' => ['Undercarriages'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Remanufactured front idler assembly for Caterpillar D6T bulldozer. Shell welded and ground to OEM spec, new floating seal and bearing.',
            'description' => '<p>Completely refurbished front idler for the Caterpillar D6T bulldozer. The idler shell has been metal-arc welded and precision ground to restore the tread to OEM diameter. New floating seal assembly and new roller bearing installed. New shaft fitted as required. Core charge of $250 applies — refunded upon receipt of serviceable core.</p><p><strong>Fits:</strong> Caterpillar D6T (all variants)</p>',
            'price' => 975.00,
            'sale_price' => null,
            'stock_quantity' => 3,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 178.0,
            'ships_worldwide' => false,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/wa250-1-main-hydraulic-pump.jpg',
        ],

        // ── ENGINES & ENGINE PARTS ────────────────────────────────────────────
        [
            'name' => 'Caterpillar 3116 Cylinder Head Assembly — Rebuilt',
            'part_number' => '2W8809',
            'oem_part_number' => '2W8809',
            'sku' => 'CAT-ENG-CH-001',
            'make' => 'Caterpillar',
            'equipment_type' => 'Excavator',
            'categories' => ['Engines & Engine Parts'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Fully remanufactured CAT 3116 cylinder head. Pressure tested, resurfaced, new valves, guides, and seals. Fits 320, 322, 325 series excavators.',
            'description' => '<p>This professionally rebuilt Caterpillar 3116 cylinder head is remanufactured to OEM specifications. Each head is completely disassembled, hot-tanked, and visually inspected. The head deck is resurfaced to OEM flatness specifications. New valves, valve guides, valve seats, valve stem seals, and head bolts are installed. The assembled head is pressure tested to 90 PSI before shipment.</p><p><strong>Fits:</strong> Caterpillar 320, 320B, 320C, 322, 325 series excavators with 3116 engine | Caterpillar 966E, 970F wheel loaders with 3116 engine</p>',
            'price' => 1299.00,
            'sale_price' => 1149.00,
            'stock_quantity' => 4,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 62.5,
            'ships_worldwide' => true,
            'is_featured' => true,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/wa250-1-main-hydraulic-pump.jpg',
        ],

        [
            'name' => 'Komatsu SAA6D107E-1 Full Gasket Set',
            'part_number' => '6754-99-6320',
            'oem_part_number' => '6754-99-6320',
            'sku' => 'KOM-ENG-GS-001',
            'make' => 'Komatsu',
            'equipment_type' => 'Excavator',
            'categories' => ['Engines & Engine Parts'],
            'condition_type' => 'new',
            'short_description' => 'Complete top-end and full engine overhaul gasket set for Komatsu SAA6D107E-1 engine. Fits PC200-8, PC210-8, PC220-8 excavators.',
            'description' => '<p>OEM-specification complete gasket set for the Komatsu SAA6D107E-1 engine. Includes the cylinder head gasket (MLS multi-layer steel), valve cover gasket, exhaust manifold gasket, intake manifold gasket, EGR gaskets, turbocharger gaskets, oil pan gasket, and all accessory O-rings and seals required for a complete top-end or full engine overhaul.</p><p><strong>Fits:</strong> Komatsu PC200-8, PC210LC-8, PC220-8, PC240LC-8 excavators with SAA6D107E-1 engine | Also fits Komatsu WA320-6 wheel loader</p>',
            'price' => 315.00,
            'sale_price' => null,
            'stock_quantity' => 12,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 5.2,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => false,
            'image_url' => 'https://files.amsparts.com/parts/RE30874.jpg',
        ],

        [
            'name' => 'John Deere PowerTech 4045 Water Pump',
            'part_number' => 'RE500734',
            'oem_part_number' => 'RE500734',
            'sku' => 'JD-ENG-WP-001',
            'make' => 'John Deere',
            'equipment_type' => 'Excavator',
            'categories' => ['Engines & Engine Parts'],
            'condition_type' => 'new',
            'short_description' => 'New OEM-quality water pump for John Deere 200G LC, 210G LC excavators with PowerTech 4045 engine. Includes gasket.',
            'description' => '<p>Direct replacement water pump for the John Deere PowerTech 4045 engine as used in the 200G LC and 210G LC excavators. Features a heavy-duty ceramic mechanical seal, cast iron housing, and precision-balanced impeller. Includes new pump-to-block gasket. Manufactured to exceed OEM specifications for longer service life.</p><p><strong>Fits:</strong> John Deere 200G LC, 210G LC, 245G LC (PowerTech 4045 engine) | John Deere 544K, 624K wheel loaders (PowerTech 4045 engine)</p>',
            'price' => 195.00,
            'sale_price' => null,
            'stock_quantity' => 8,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 8.2,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => false,
            'image_url' => 'https://files.amsparts.com/parts/RE505980.jpg',
        ],

        [
            'name' => 'John Deere PowerTech 6068 Water Pump',
            'part_number' => 'RE505980',
            'oem_part_number' => 'RE505980',
            'sku' => 'JD-ENG-WP-002',
            'make' => 'John Deere',
            'equipment_type' => 'Excavator',
            'categories' => ['Engines & Engine Parts'],
            'condition_type' => 'new',
            'short_description' => 'New replacement water pump for John Deere PowerTech 6068 engine. Weight: 8.7 lbs. Fits multiple excavator, wheel loader, and backhoe models.',
            'description' => '<p>High-quality replacement water pump for the John Deere PowerTech 6068 engine family. Heavy-duty mechanical seal and balanced impeller. Includes mounting gasket. Fits multiple John Deere construction equipment models with the 6068 engine including larger excavators, wheel loaders, and backhoe loaders.</p><p><strong>Part #:</strong> RE505980 | <strong>Weight:</strong> 8.7 lbs</p>',
            'price' => 215.00,
            'sale_price' => null,
            'stock_quantity' => 6,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 8.7,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => false,
            'image_url' => 'https://files.amsparts.com/parts/RE505980.jpg',
        ],

        [
            'name' => 'John Deere 210C / 350B Water Pump',
            'part_number' => 'RE25043',
            'oem_part_number' => 'RE25043',
            'sku' => 'JD-ENG-WP-003',
            'make' => 'John Deere',
            'equipment_type' => 'Excavator',
            'categories' => ['Engines & Engine Parts'],
            'condition_type' => 'new',
            'short_description' => 'New water pump for John Deere 210C and 350B excavators. Weight: 22 lbs.',
            'description' => '<p>Replacement water pump for John Deere 210C and 350B construction equipment. Cast iron housing with ceramic mechanical seal for long service life. Includes new pump gasket.</p><p><strong>Fits:</strong> John Deere 210C, 350B | <strong>Part #:</strong> RE25043 | <strong>Weight:</strong> 22 lbs</p>',
            'price' => 245.00,
            'sale_price' => null,
            'stock_quantity' => 4,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 22.0,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => false,
            'image_url' => 'https://files.amsparts.com/parts/RE25043.jpg',
        ],

        [
            'name' => 'Caterpillar 3306 Engine Piston Kit — Set of 6',
            'part_number' => '7W2326',
            'oem_part_number' => '7W2326',
            'sku' => 'CAT-ENG-PK-001',
            'make' => 'Caterpillar',
            'equipment_type' => 'Bulldozer',
            'categories' => ['Engines & Engine Parts'],
            'condition_type' => 'new',
            'short_description' => 'New piston and ring kit for all 6 cylinders of the Caterpillar 3306 engine. Fits D6R, D7R bulldozers and 966E, 970F wheel loaders.',
            'description' => '<p>Complete piston kit including 6 pistons, ring sets (compression and oil), wrist pins, and pin retainers for the Caterpillar 3306 engine. Pistons are manufactured to exact OEM dimensions with proper crown geometry for correct combustion. Rings are manufactured from centrifugally cast ductile iron with chrome facing on the top compression ring.</p><p><strong>Fits:</strong> Caterpillar 3306 engine — D6R, D7R bulldozers | 966E, 970F wheel loaders | 16G, 24H motor graders</p>',
            'price' => 975.00,
            'sale_price' => null,
            'stock_quantity' => 2,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 32.0,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/wa250-1-main-hydraulic-pump.jpg',
        ],

        // ── SEAL KITS ─────────────────────────────────────────────────────────
        [
            'name' => 'John Deere Hydraulic Cylinder Seal Kit',
            'part_number' => 'RE30874',
            'oem_part_number' => 'RE30874',
            'sku' => 'JD-SK-001',
            'make' => 'John Deere',
            'equipment_type' => 'Excavator',
            'categories' => ['Seal Kits'],
            'condition_type' => 'new',
            'short_description' => 'OEM-spec hydraulic cylinder seal kit for John Deere equipment. Weight: 0.20 lbs. Polyurethane and Viton seals for extended service life.',
            'description' => '<p>Hydraulic cylinder seal kit for John Deere construction equipment. Contains all necessary seals including piston seal, rod seal, wear rings, dust seal, and O-rings. All seals manufactured from polyurethane or Viton elastomers for compatibility with all mineral-based and many synthetic hydraulic fluids.</p><p><strong>Part #:</strong> RE30874 | <strong>Weight:</strong> 0.20 lbs</p>',
            'price' => 42.00,
            'sale_price' => null,
            'stock_quantity' => 50,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 0.2,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => false,
            'image_url' => 'https://files.amsparts.com/parts/RE30874.jpg',
        ],

        [
            'name' => 'John Deere 400G Hydraulic Cylinder Seal Kit',
            'part_number' => 'RE20433',
            'oem_part_number' => 'RE20433',
            'sku' => 'JD-SK-002',
            'make' => 'John Deere',
            'equipment_type' => 'Excavator',
            'categories' => ['Seal Kits'],
            'condition_type' => 'new',
            'short_description' => 'Hydraulic cylinder seal kit for John Deere 400G. Weight: 0.31 lbs.',
            'description' => '<p>Hydraulic cylinder seal kit for the John Deere 400G. All seals meet or exceed OEM specifications. Kit includes all seals, O-rings, and backup rings required for a complete cylinder reseal.</p><p><strong>Fits:</strong> John Deere 400G | <strong>Part #:</strong> RE20433 | <strong>Weight:</strong> 0.31 lbs</p>',
            'price' => 38.00,
            'sale_price' => null,
            'stock_quantity' => 40,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 0.31,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => false,
            'image_url' => 'https://files.amsparts.com/parts/RE20433.jpg',
        ],

        [
            'name' => 'John Deere Bore Seal Kit',
            'part_number' => 'RE16076',
            'oem_part_number' => 'RE16076',
            'sku' => 'JD-SK-003',
            'make' => 'John Deere',
            'equipment_type' => 'Excavator',
            'categories' => ['Seal Kits'],
            'condition_type' => 'new',
            'short_description' => 'Hydraulic cylinder bore seal kit for John Deere construction equipment. Weight: 0.20 lbs.',
            'description' => '<p>Bore-side seal kit for John Deere hydraulic cylinders. Includes piston seal, wear rings, and O-rings for the piston/bore end of the cylinder. High-quality polyurethane and nitrile rubber seals for extended service life.</p><p><strong>Part #:</strong> RE16076 | <strong>Weight:</strong> 0.20 lbs</p>',
            'price' => 35.00,
            'sale_price' => null,
            'stock_quantity' => 55,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 0.2,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => false,
            'image_url' => 'https://files.amsparts.com/parts/RE16076.jpg',
        ],

        [
            'name' => 'Komatsu PC200-8 Boom Cylinder Seal Kit',
            'part_number' => '707-98-45230',
            'oem_part_number' => '707-98-45230',
            'sku' => 'KOM-SK-001',
            'make' => 'Komatsu',
            'equipment_type' => 'Excavator',
            'categories' => ['Seal Kits'],
            'condition_type' => 'new',
            'short_description' => 'Complete OEM-spec boom cylinder seal kit for Komatsu PC200-8 excavator. Polyurethane and Viton seals.',
            'description' => '<p>Full boom cylinder seal kit for the Komatsu PC200-8 excavator. Kit includes piston seal (polyurethane), rod seal (polyurethane), wear ring, dust seal, and all O-rings for the boom cylinder. All seals are manufactured from polyurethane or Viton for extended service life and resistance to biodegradable hydraulic fluids.</p><p><strong>Fits:</strong> Komatsu PC200-8 boom cylinder</p>',
            'price' => 95.00,
            'sale_price' => null,
            'stock_quantity' => 28,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 0.9,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => false,
            'image_url' => 'https://files.amsparts.com/parts/RE30874.jpg',
        ],

        // ── RADIATORS ─────────────────────────────────────────────────────────
        [
            'name' => 'Caterpillar 320D Radiator Assembly',
            'part_number' => '283-5246',
            'oem_part_number' => '283-5246',
            'sku' => 'CAT-RAD-001',
            'make' => 'Caterpillar',
            'equipment_type' => 'Excavator',
            'categories' => ['Radiators'],
            'condition_type' => 'new',
            'short_description' => 'New aluminum-core radiator assembly for CAT 320D, 320DL excavators. Pressure tested. Direct bolt-on replacement.',
            'description' => '<p>Heavy-duty aluminum brazed-core radiator for the Caterpillar 320D and 320DL excavator. Features an all-aluminum core with plastic-composite tanks. Pressure tested to 30 PSI. Includes all mounting brackets and hose connections for direct bolt-on installation. Identical fit to OEM unit at significantly lower cost.</p><p><strong>Fits:</strong> Caterpillar 320D, 320DL, 320DRR</p>',
            'price' => 1195.00,
            'sale_price' => null,
            'stock_quantity' => 3,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 58.0,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => false,
            'image_url' => 'https://files.amsparts.com/parts/wa250-1-main-hydraulic-pump.jpg',
        ],

        // ── TRANSMISSIONS ─────────────────────────────────────────────────────
        [
            'name' => 'Caterpillar 950H Torque Converter — Rebuilt',
            'part_number' => '291-8970',
            'oem_part_number' => '291-8970',
            'sku' => 'CAT-TRANS-TC-001',
            'make' => 'Caterpillar',
            'equipment_type' => 'Wheel Loader',
            'categories' => ['Transmissions'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Remanufactured torque converter for Caterpillar 950H wheel loader. All friction surfaces lapped, new seals and bearings. Core exchange required.',
            'description' => '<p>Professionally remanufactured torque converter for the Caterpillar 950H wheel loader. All friction clutch surfaces are lapped and inspected. The converter housing is pressure washed and inspected for cracks. New seals, bearings, and thrust washers are installed. Unit is balanced and pressure tested. A $350 core charge applies and will be refunded upon receipt of a serviceable core within 30 days.</p><p><strong>Fits:</strong> Caterpillar 950H, 950M wheel loaders</p>',
            'price' => 2950.00,
            'sale_price' => null,
            'stock_quantity' => 1,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 215.0,
            'ships_worldwide' => false,
            'is_featured' => true,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/sk330lc-hydraulic-pump.jpg',
        ],

        [
            'name' => 'Komatsu WA470-6 Transmission Filter Kit',
            'part_number' => '21W-60-71110',
            'oem_part_number' => '21W-60-71110',
            'sku' => 'KOM-TRANS-FK-001',
            'make' => 'Komatsu',
            'equipment_type' => 'Wheel Loader',
            'categories' => ['Transmissions', 'Filters & Maintenance'],
            'condition_type' => 'new',
            'short_description' => 'Complete transmission service kit for Komatsu WA470-6 wheel loader. Includes main filter, strainer, and all gaskets.',
            'description' => '<p>Complete transmission service filter kit for the Komatsu WA470-6 wheel loader. Kit includes the main transmission filter element, the suction strainer, all required O-rings and gaskets for a complete transmission service. All components meet or exceed OEM specifications.</p><p><strong>Fits:</strong> Komatsu WA470-6</p>',
            'price' => 155.00,
            'sale_price' => null,
            'stock_quantity' => 18,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 4.2,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => false,
            'image_url' => 'https://files.amsparts.com/parts/RE30874.jpg',
        ],

        // ── FILTERS & MAINTENANCE ─────────────────────────────────────────────
        [
            'name' => 'Caterpillar 320D Full Service Filter Kit',
            'part_number' => 'CAT-FK-320D',
            'oem_part_number' => null,
            'sku' => 'CAT-FLT-KIT-001',
            'make' => 'Caterpillar',
            'equipment_type' => 'Excavator',
            'categories' => ['Filters & Maintenance'],
            'condition_type' => 'new',
            'short_description' => 'Complete service kit for CAT 320D: engine oil filter, primary fuel filter, secondary fuel filter, outer air filter, inner air safety, and hydraulic return filter.',
            'description' => '<p>Everything needed for a full scheduled service on the Caterpillar 320D excavator. This kit includes the engine oil filter (1R-0716), primary fuel filter (326-1643), secondary fuel filter (1R-0750), outer air filter element (1R-0727), inner air filter safety element (1R-0728), and hydraulic oil return filter (093-7521). All filters meet or exceed OEM specifications.</p><p><strong>Fits:</strong> Caterpillar 320D, 320DL, 320DRR (all serial prefixes)</p>',
            'price' => 139.00,
            'sale_price' => 115.00,
            'stock_quantity' => 40,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 7.0,
            'ships_worldwide' => true,
            'is_featured' => true,
            'status' => 'active',
            'california_prop65' => false,
            'image_url' => 'https://files.amsparts.com/parts/RE30874.jpg',
        ],

        [
            'name' => 'Komatsu PC200-8 Engine Oil Filter',
            'part_number' => '600-211-1231',
            'oem_part_number' => '600-211-1231',
            'sku' => 'KOM-FLT-OF-001',
            'make' => 'Komatsu',
            'equipment_type' => 'Excavator',
            'categories' => ['Filters & Maintenance'],
            'condition_type' => 'new',
            'short_description' => 'High-quality engine oil filter for Komatsu PC200-8, PC210LC-8, PC220-8 excavators with SAA6D107E-1 engine.',
            'description' => '<p>High-efficiency spin-on engine oil filter for the Komatsu SAA6D107E-1 engine. Features an anti-drain-back valve to retain oil in the filter during shutdown, a heavy-duty bypass spring set to OEM specification, and a high-capacity filter media. Compatible with all conventional and synthetic engine oils.</p><p><strong>Fits:</strong> Komatsu PC200-8, PC210LC-8, PC220-8, PC240LC-8 (SAA6D107E-1 engine) | Komatsu WA320-6, WA380-6 (SAA6D107E-1 engine)</p>',
            'price' => 28.00,
            'sale_price' => null,
            'stock_quantity' => 75,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 1.1,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => false,
            'image_url' => 'https://files.amsparts.com/parts/RE30874.jpg',
        ],

        // ── ELECTRICAL COMPONENTS ─────────────────────────────────────────────
        [
            'name' => 'Caterpillar 320D Alternator 24V 45A — Rebuilt',
            'part_number' => '258-5466',
            'oem_part_number' => '258-5466',
            'sku' => 'CAT-ELEC-ALT-001',
            'make' => 'Caterpillar',
            'equipment_type' => 'Excavator',
            'categories' => ['Electrical Components'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Remanufactured 24V 45-amp alternator for CAT 320D, 320DL, 325D excavators. New rotor, stator, rectifier, and voltage regulator.',
            'description' => '<p>Completely rebuilt 24-volt 45-amp alternator for the Caterpillar 320D, 320DL, and 325D excavators. Each unit is completely disassembled and rebuilt with new rotor windings, stator windings, full-wave bridge rectifier, voltage regulator, brush assembly, front and rear bearings, and internal fan. The rebuilt alternator is load-tested at 100% capacity on a dedicated alternator test bench before shipping.</p><p><strong>Fits:</strong> Caterpillar 320D, 320DL, 320DRR, 325D (C6.4 engine)</p>',
            'price' => 345.00,
            'sale_price' => 295.00,
            'stock_quantity' => 6,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 13.0,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/wa250-1-main-hydraulic-pump.jpg',
        ],

        [
            'name' => 'John Deere 200G / 210G Starter Motor 24V',
            'part_number' => 'RE501937',
            'oem_part_number' => 'RE501937',
            'sku' => 'JD-ELEC-SM-001',
            'make' => 'John Deere',
            'equipment_type' => 'Excavator',
            'categories' => ['Electrical Components'],
            'condition_type' => 'new',
            'short_description' => 'New 24V heavy-duty starter motor for John Deere 200G LC, 210G LC excavators with PowerTech 4045 engine.',
            'description' => '<p>New heavy-duty 24-volt starter motor for the John Deere 200G LC and 210G LC excavators with PowerTech 4045 engine. Manufactured to exceed OEM specifications with sealed ball bearings, a heavy-duty solenoid with copper contacts, and a high-torque drive assembly. Includes all mounting hardware and a new ground cable. Drop-in installation with no modifications required.</p><p><strong>Fits:</strong> John Deere 200G LC, 210G LC (PowerTech 4045 engine)</p>',
            'price' => 415.00,
            'sale_price' => null,
            'stock_quantity' => 5,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 18.5,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/wa250-1-main-hydraulic-pump.jpg',
        ],

        // ── FUEL SYSTEM ───────────────────────────────────────────────────────
        [
            'name' => 'Komatsu PC200-8 Fuel Injection Pump — Rebuilt',
            'part_number' => '6754-71-1310',
            'oem_part_number' => '6754-71-1310',
            'sku' => 'KOM-FUEL-IP-001',
            'make' => 'Komatsu',
            'equipment_type' => 'Excavator',
            'categories' => ['Fuel System'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Remanufactured fuel injection pump for Komatsu PC200-8 with SAA6D107E-1 engine. Flow-tested and calibrated.',
            'description' => '<p>Completely rebuilt fuel injection pump for the Komatsu PC200-8 excavator with SAA6D107E-1 engine. All plunger elements, delivery valves, and internal seals are replaced. The pump is calibrated on a dedicated injection pump test stand to OEM fuel delivery specifications at all RPM ranges. Includes new O-rings, gaskets, and a new governor spring set.</p><p><strong>Fits:</strong> Komatsu PC200-8, PC210LC-8 with SAA6D107E-1 engine</p>',
            'price' => 1650.00,
            'sale_price' => 1499.00,
            'stock_quantity' => 2,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 22.5,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/wa250-1-main-hydraulic-pump.jpg',
        ],

        [
            'name' => 'Caterpillar 3116 Fuel Injector Set of 6 — Rebuilt',
            'part_number' => '0R-4608',
            'oem_part_number' => '0R-4608',
            'sku' => 'CAT-FUEL-INJ-001',
            'make' => 'Caterpillar',
            'equipment_type' => 'Excavator',
            'categories' => ['Fuel System'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Set of 6 remanufactured fuel injectors for CAT 3116 engine. Ultrasonic cleaned, new nozzle tips and O-rings, tested to OEM spray pattern.',
            'description' => '<p>Set of 6 fully remanufactured CAT 3116 fuel injectors. Each injector is completely disassembled, ultrasonically cleaned, inspected, fitted with a new nozzle tip assembly and O-rings, and tested on a certified injector pop tester for correct opening pressure, spray pattern, and atomization. Core exchange required — $120 core charge refunded on return of 6 serviceable core injectors.</p><p><strong>Fits:</strong> Caterpillar 3116 engine — 320, 322, 325 series excavators | 966E wheel loaders | TH63 telehandler</p>',
            'price' => 1150.00,
            'sale_price' => null,
            'stock_quantity' => 3,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 9.0,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/wa250-1-main-hydraulic-pump.jpg',
        ],

        // ── GROUND ENGAGING TOOLS ─────────────────────────────────────────────
        [
            'name' => 'Caterpillar J350 General Purpose Bucket Teeth — 5 Pack',
            'part_number' => '1U-3202',
            'oem_part_number' => '1U-3202',
            'sku' => 'CAT-GET-TOOTH-001',
            'make' => 'Caterpillar',
            'equipment_type' => 'Excavator',
            'categories' => ['Ground Engaging Tools'],
            'condition_type' => 'new',
            'short_description' => 'Heavy-duty J350 twin-pin general purpose bucket teeth for CAT 320–336 excavators. High-alloy steel with through-hardened tip. 5-pack.',
            'description' => '<p>Caterpillar-compatible J350 twin-pin general purpose teeth manufactured from high-alloy steel with a through-hardened cutting tip for maximum penetration and wear life. Fits J350 series adapters as found on Caterpillar 320D, 323D, 329D, 330D, 336D series excavators. Sold as a 5-pack.</p><p><strong>Fits:</strong> J350 adapter system — CAT 320D, 323D, 325D, 329D, 330D, 336D</p><p><strong>Qty:</strong> 5 teeth per pack | <strong>Weight:</strong> 28 lbs per pack</p>',
            'price' => 195.00,
            'sale_price' => null,
            'stock_quantity' => 60,
            'stock_status' => 'in_stock',
            'warranty_type' => '90_days',
            'weight_lbs' => 28.0,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => false,
            'image_url' => 'https://files.amsparts.com/parts/wa250-1-main-hydraulic-pump.jpg',
        ],

        [
            'name' => 'Caterpillar D6T Center Cutting Edge',
            'part_number' => '9W1855',
            'oem_part_number' => '9W1855',
            'sku' => 'CAT-GET-CE-001',
            'make' => 'Caterpillar',
            'equipment_type' => 'Bulldozer',
            'categories' => ['Ground Engaging Tools'],
            'condition_type' => 'new',
            'short_description' => 'Heavy-duty boron steel center cutting edge for Caterpillar D6T bulldozer blade. 16-bolt mounting pattern.',
            'description' => '<p>Boron steel center cutting edge for the Caterpillar D6T bulldozer semi-U and straight blade configurations. 16-bolt mounting pattern. Manufactured from heat-treated boron steel for superior abrasion resistance. Compatible with standard and abrasion-resistant (AR) blade configurations.</p><p><strong>Fits:</strong> Caterpillar D6T (all blade variants using 9W1855) | <strong>Bolts:</strong> 16 | <strong>Weight:</strong> 95 lbs</p>',
            'price' => 445.00,
            'sale_price' => null,
            'stock_quantity' => 8,
            'stock_status' => 'in_stock',
            'warranty_type' => '90_days',
            'weight_lbs' => 95.0,
            'ships_worldwide' => false,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => false,
            'image_url' => 'https://files.amsparts.com/parts/sk330lc-hydraulic-pump.jpg',
        ],

        // ── AXLES & DRIVETRAINS ───────────────────────────────────────────────
        [
            'name' => 'Caterpillar 950H Front Axle Differential Assembly',
            'part_number' => '175-3481',
            'oem_part_number' => '175-3481',
            'sku' => 'CAT-AXLE-FD-001',
            'make' => 'Caterpillar',
            'equipment_type' => 'Wheel Loader',
            'categories' => ['Axles & Drivetrains'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Remanufactured front axle differential for Caterpillar 950H wheel loader. All bearings, ring-and-pinion, and seals replaced.',
            'description' => '<p>Professionally remanufactured front axle differential assembly for the Caterpillar 950H wheel loader. Ring-and-pinion gear set is inspected and replaced as needed. All roller and tapered bearings are replaced. New axle shaft seals and pinion seal installed. Unit is set up to OEM backlash and pre-load specifications before shipment.</p><p><strong>Fits:</strong> Caterpillar 950H, 950M wheel loaders (front axle)</p>',
            'price' => 3850.00,
            'sale_price' => null,
            'stock_quantity' => 1,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 380.0,
            'ships_worldwide' => false,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/sk330lc-hydraulic-pump.jpg',
        ],

        // ── CABS ──────────────────────────────────────────────────────────────
        [
            'name' => 'Caterpillar 320D Front Windshield Glass',
            'part_number' => '273-3200',
            'oem_part_number' => '273-3200',
            'sku' => 'CAT-CAB-WS-001',
            'make' => 'Caterpillar',
            'equipment_type' => 'Excavator',
            'categories' => ['Cabs'],
            'condition_type' => 'new',
            'short_description' => 'New OEM-spec tempered front windshield glass for Caterpillar 320D, 320D2 excavator cab.',
            'description' => '<p>New tempered safety glass front windshield for the Caterpillar 320D and 320D2 excavator cab. Manufactured to OEM specifications for correct fit and visibility. Tempered for operator safety. Direct replacement with no cab modifications required. Includes new rubber seal.</p><p><strong>Fits:</strong> Caterpillar 320D, 320DL, 320D2 excavator cab</p>',
            'price' => 285.00,
            'sale_price' => null,
            'stock_quantity' => 5,
            'stock_status' => 'in_stock',
            'warranty_type' => '90_days',
            'weight_lbs' => 22.0,
            'ships_worldwide' => false,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => false,
            'image_url' => 'https://files.amsparts.com/parts/wa250-1-main-hydraulic-pump.jpg',
        ],

        // ── FEATURED MULTI-MAKE / OUT-OF-STOCK EXAMPLES ───────────────────────
        [
            'name' => 'Volvo EC300D Swing Motor Assembly — Rebuilt',
            'part_number' => 'VOE14620773',
            'oem_part_number' => 'VOE14620773',
            'sku' => 'VOL-SM-001',
            'make' => 'Volvo',
            'equipment_type' => 'Excavator',
            'categories' => ['Swing Machinery'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Remanufactured swing motor with planetary reduction gearbox for Volvo EC300D excavator. New seals, bearings, and brake discs.',
            'description' => '<p>Complete remanufactured swing drive assembly for the Volvo EC300D hydraulic excavator. Includes the hydraulic swing motor and integrated planetary reduction gearbox. All planetary gears are inspected and replaced as needed. New roller bearings, new mechanical seals, and new parking brake disc assembly installed. Motor rebuilt with new pistons, barrel, valve plate, and shaft seal, then tested for proper torque output.</p><p><strong>Fits:</strong> Volvo EC300D</p>',
            'price' => 4350.00,
            'sale_price' => 3950.00,
            'stock_quantity' => 1,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 285.0,
            'ships_worldwide' => true,
            'is_featured' => true,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/sk330lc-hydraulic-pump.jpg',
        ],

        [
            'name' => 'Doosan DX300LC-5 Main Hydraulic Pump — Rebuilt',
            'part_number' => '400914-00196',
            'oem_part_number' => '400914-00196',
            'sku' => 'DOO-HYD-HP-001',
            'make' => 'Doosan',
            'equipment_type' => 'Excavator',
            'categories' => ['Hydraulic Pumps'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Remanufactured dual main hydraulic pump for Doosan DX300LC-5 excavator. Pressure and flow tested.',
            'description' => '<p>Remanufactured main hydraulic pump for the Doosan DX300LC-5 excavator. Dual-pump assembly is completely disassembled, all internal wear components replaced, and the unit is pressure and flow tested on a dedicated test stand before shipping.</p><p><strong>Fits:</strong> Doosan DX300LC-5</p>',
            'price' => 3650.00,
            'sale_price' => null,
            'stock_quantity' => 0,
            'stock_status' => 'on_order',
            'warranty_type' => '1_year',
            'weight_lbs' => 148.0,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/sk330lc-hydraulic-pump.jpg',
        ],

        [
            'name' => 'Case CX350D Final Drive Assembly — Rebuilt',
            'part_number' => 'KBA2455',
            'oem_part_number' => 'KBA2455',
            'sku' => 'CAS-FD-001',
            'make' => 'Case',
            'equipment_type' => 'Excavator',
            'categories' => ['Final Drives'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Remanufactured travel final drive assembly with motor for Case CX350D excavator. All bearings, seals, and motor components replaced.',
            'description' => '<p>Completely remanufactured final drive assembly for the Case CX350D excavator. Includes the hydraulic travel motor and planetary reduction unit. All bearings replaced, new mechanical face seals installed. Motor rebuilt with new pistons, barrel, valve plate, and shaft seal, then bench tested for correct displacement and zero internal bypass.</p><p><strong>Fits:</strong> Case CX350D</p>',
            'price' => 5650.00,
            'sale_price' => 5100.00,
            'stock_quantity' => 1,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 430.0,
            'ships_worldwide' => false,
            'is_featured' => true,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/th9195238.jpg',
        ],

        [
            'name' => 'Bobcat S650 Hydraulic Drive Motor — Rebuilt',
            'part_number' => '7170651',
            'oem_part_number' => '7170651',
            'sku' => 'BOB-HYD-DM-001',
            'make' => 'Bobcat',
            'equipment_type' => 'Skid Steer',
            'categories' => ['Hydraulic Pumps'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Remanufactured hydraulic drive motor for Bobcat S650 skid steer loader. Dyno-tested for correct torque and zero internal leakage.',
            'description' => '<p>Fully rebuilt hydraulic drive motor for the Bobcat S650 skid steer loader. New roller bearings, new shaft seal, new piston and barrel assembly. Dyno-tested to verify correct torque output and zero internal bypass before shipping.</p><p><strong>Fits:</strong> Bobcat S650</p>',
            'price' => 895.00,
            'sale_price' => null,
            'stock_quantity' => 2,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 36.0,
            'ships_worldwide' => true,
            'is_featured' => true,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/sk330lc-hydraulic-pump.jpg',
        ],

        [
            'name' => 'Hitachi ZX200-5G Arm Cylinder — Rebuilt',
            'part_number' => '4633396',
            'oem_part_number' => '4633396',
            'sku' => 'HIT-CYL-ARM-001',
            'make' => 'Hitachi',
            'equipment_type' => 'Excavator',
            'categories' => ['Hydraulic Cylinders'],
            'condition_type' => 'rebuilt',
            'short_description' => 'Remanufactured arm cylinder for Hitachi ZX200-5G excavator. Bore honed to OEM spec, new seals, chrome rod inspected.',
            'description' => '<p>Remanufactured arm (stick) cylinder for the Hitachi ZX200-5G excavator. The cylinder bore is honed to OEM specification. The chrome rod is inspected for scoring and chrome integrity — rods with defects are replaced. Complete new seal kit installed. The assembled cylinder is pressure tested before shipment.</p><p><strong>Fits:</strong> Hitachi ZX200-5G</p>',
            'price' => 1850.00,
            'sale_price' => null,
            'stock_quantity' => 2,
            'stock_status' => 'in_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 92.0,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => true,
            'image_url' => 'https://files.amsparts.com/parts/th9195238.jpg',
        ],

        [
            'name' => 'Komatsu PC360LC-10 Boom Cylinder Chrome Rod',
            'part_number' => '707-01-XD751',
            'oem_part_number' => '707-01-XD751',
            'sku' => 'KOM-CYL-ROD-001',
            'make' => 'Komatsu',
            'equipment_type' => 'Excavator',
            'categories' => ['Hydraulic Cylinders'],
            'condition_type' => 'new',
            'short_description' => 'New hard chrome-plated boom cylinder rod for Komatsu PC360LC-10 excavator. Ground to OEM diameter, ready to install.',
            'description' => '<p>New hard chrome plated boom cylinder rod for the Komatsu PC360LC-10 excavator. The rod is ground to OEM diameter and straightness tolerances. Hard chrome layer thickness is verified. All dimensions confirmed before shipping. Install with your existing seal kit or order kit separately.</p><p><strong>Fits:</strong> Komatsu PC360LC-10 boom cylinder</p>',
            'price' => 820.00,
            'sale_price' => null,
            'stock_quantity' => 0,
            'stock_status' => 'out_of_stock',
            'warranty_type' => '1_year',
            'weight_lbs' => 68.0,
            'ships_worldwide' => true,
            'is_featured' => false,
            'status' => 'active',
            'california_prop65' => false,
            'image_url' => 'https://files.amsparts.com/parts/sk330lc-hydraulic-pump.jpg',
        ],
    ];

    // ────────────────────────────────────────────────────────────────────────

    public function run(): void
    {
        $this->command->info('Seeding Parts...');

        foreach ($this->parts as $partData) {
            $this->command->line("  → {$partData['name']}");

            // Look up parent relationships
            $make = Make::where('name', $partData['make'])->first();
            $eqType = EquipmentType::where('name', $partData['equipment_type'])->first();

            // Safe category extract
            $categoryNames = $partData['categories'];

            // Build unique slug string
            $slug = Str::slug($partData['name']);

            // Download/get image
            $imageUrl = $partData['image_url'] ?? null;
            $mediaId = null;
            if ($imageUrl) {
                $mediaId = $this->downloadImage(
                    $imageUrl,
                    'parts',
                    $partData['name']
                );
            }

            // Clean out data array parameters not native to parts database table columns
            unset($partData['make'], $partData['equipment_type'], $partData['categories'], $partData['image_url']);

            // Save entry matching the array schema payload
            $part = Part::updateOrCreate(
                ['slug' => $slug],
                array_merge($partData, [
                    'slug' => $slug,
                    'make_id' => $make?->id ?? 1, // Fallback safe protection
                    'equipment_type_id' => $eqType?->id ?? 1,
                    'primary_image_id' => $mediaId,
                    'views' => $partData['views'] ?? rand(50, 500),
                ])
            );

            // Create PartImage entry if we have a mediaId
            if ($mediaId) {
                PartImage::updateOrCreate(
                    [
                        'part_id' => $part->id,
                        'media_library_id' => $mediaId,
                    ],
                    [
                        'part_id' => $part->id,
                        'media_library_id' => $mediaId,
                        'sort_order' => 0,
                        'is_main' => true,
                    ]
                );
            }

            // Sync many-to-many bridge constraints
            $categoryIds = Category::whereIn('name', $categoryNames)->pluck('id');
            $part->categories()->sync($categoryIds);
        }
    }

}
